from __future__ import annotations

import re
from pathlib import Path

import typer

from .fastapi_template import create_fastapi_template
from .flask_template import create_flask_template
from .models import CliAiProvider, Template
from .worker_template import create_worker_template



app = typer.Typer(help="Optimation CLI")


def _package_name(name: str) -> str:
    name = name.strip().lower()
    name = re.sub(r"[^a-z0-9_]+", "_", name)
    name = re.sub(r"_+", "_", name).strip("_")
    if not name:
        return "optimation_project"
    if name[0].isdigit():
        return f"optimation_{name}"
    return name


@app.command()
def init(
    name: str,
    path: str,
    template: Template = typer.Option(Template.FLASK,'--template','-t'),
    coding_agent: CliAiProvider = typer.Option(CliAiProvider.CODEX, "--agent", "-a")
    ) -> None:
    """
    Crée un projet standard Optimation (api/domain/services).
    Simple, sans templates complexes pour l’instant.
    """
    project = _package_name(name)
    root = Path(path)

    if root.exists() and path != '.':
        raise typer.BadParameter(f"Folder already exists: {root}")

    (root / "src" / project / "api").mkdir(parents=True)
    (root / "src" / project / "domain").mkdir(parents=True)
    (root / "src" / project / "services").mkdir(parents=True)
    (root / "tests").mkdir(parents=True)

    (root / "src" / project / "__init__.py").write_text("", encoding="utf-8")
    (root / "src" / project / "api" / "__init__.py").write_text("", encoding="utf-8")
    (root / "src" / project / "domain" / "__init__.py").write_text("", encoding="utf-8")
    (root / "src" / project / "services" / "__init__.py").write_text("", encoding="utf-8")

    (root / ".env.example").write_text(
        "OPTIMATION_ENV=dev\nOPTIMATION_LOG_LEVEL=INFO\n",
        encoding="utf-8",
    )

    (root / "README.md").write_text(
        f"# {project}\n\nGenerated by Optimation CLI.\n",
        encoding="utf-8",
    )

    if coding_agent == CliAiProvider.CODEX:
        (root / "AGENT.md").write_text(
            """
                Yo man ho yo do today
                brin me some beer
            """
        )

    if template == Template.FLASK:
        create_flask_template(root, project)
    elif template == Template.FAST_API:
        create_fastapi_template(root, project)
    elif template == Template.WORKER:
        create_worker_template(root, project)
    else:
        raise typer.BadParameter(f"Unsupported template: {template}")

    typer.echo(f"Created project: {root}")

@app.command()
def doctor():
    typer.echo("Doctor check: OK")

    
if __name__ == "__main__":
    app()
