from __future__ import annotations

import re
from pathlib import Path

import typer

from .models import CliAiProvider, Template



app = typer.Typer(help="Optimation CLI")


def _slug(name: str) -> str:
    name = name.strip().lower()
    name = re.sub(r"[^a-z0-9]+", "-", name)
    return name.strip("-") or "optimation-project"


@app.command()
def init(
    name: str,
    path: str,
    template: Template = typer.Option(Template.FLASK,'--template','-t'),
    coding_agent: CliAiProvider = typer.Option(CliAiProvider.CODEX, "--agent", "-a")
    ) -> None:
    """
    Crée un projet standard Optimation (api/domain/services).
    Simple, sans templates complexes pour l’instant.
    """
    project = _slug(name)
    root = Path(path)

    if root.exists() and path != '.':
        raise typer.BadParameter(f"Folder already exists: {root}")

    (root / "src" / project / "api").mkdir(parents=True)
    (root / "src" / project / "domain").mkdir(parents=True)
    (root / "src" / project / "services").mkdir(parents=True)
    (root / "tests").mkdir(parents=True)

    (root / "src" / project / "__init__.py").write_text("", encoding="utf-8")
    (root / "src" / project / "api" / "__init__.py").write_text("", encoding="utf-8")
    (root / "src" / project / "domain" / "__init__.py").write_text("", encoding="utf-8")
    (root / "src" / project / "services" / "__init__.py").write_text("", encoding="utf-8")

    (root / ".env.example").write_text(
        "OPTIMATION_ENV=dev\nOPTIMATION_LOG_LEVEL=INFO\n",
        encoding="utf-8",
    )

    (root / "README.md").write_text(
        f"# {project}\n\nGenerated by Optimation CLI.\n",
        encoding="utf-8",
    )

    if coding_agent == 'codex':
        (root / "AGENT.md").write_text(
            """
                Yo man ho yo do today
                brin me some beer
            """
        )

    # Template simple: worker vs fastapi (placeholder)
    if template == "fastapi":
        (root / "src" / project / "main.py").write_text(
            "def main():\n    print('Hello from FastAPI template (TODO)')\n\n"
            "if __name__ == '__main__':\n    main()\n",
            encoding="utf-8",
        )
    else:
        (root / "src" / project / "main.py").write_text(
            "def main():\n    print('Hello from worker template')\n\n"
            "if __name__ == '__main__':\n    main()\n",
            encoding="utf-8",
        )

    typer.echo(f"✅ Created project: {root}")

@app.command()
def doctor():
    typer.echo("🧑‍⚕️ i'm a doctor")

    
if __name__ == "__main__":
    app()
