from __future__ import annotations

from pathlib import Path


BASE_HTML_TEMPLATE = """<!doctype html>
<html lang='en'>
<head>
  <meta charset='utf-8'>
  <meta name='viewport' content='width=device-width, initial-scale=1'>
  <title>{% block title %}{{ app_name }}{% endblock %}</title>
  <link rel='preconnect' href='https://cdn.jsdelivr.net'>
  <link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css'>
  <link rel='stylesheet' href='__CSS_HREF__'>
</head>
<body>
  <nav class='navbar navbar-expand-lg navbar-dark bg-primary shadow-sm'>
    <div class='container'>
      <a class='navbar-brand fw-semibold' href='#'>{{ app_name }}</a>
    </div>
  </nav>
  <main class='py-5'>
    <div class='container'>
      {% block content %}{% endblock %}
    </div>
  </main>
  <script src='https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js'></script>
  <script src='__JS_SRC__'></script>
</body>
</html>
"""

INDEX_HTML_TEMPLATE = """{% extends 'base.html' %}
{% block title %}Dashboard - {{ app_name }}{% endblock %}
{% block content %}
  <div class='p-4 p-md-5 mb-4 rounded-3 bg-light border'>
    <div class='col-lg-8 px-0'>
      <h1 class='display-6 fw-bold text-primary mb-3'>{{ app_name }}</h1>
      <p class='lead mb-4'>__DESCRIPTION__</p>
      <a class='btn btn-primary btn-lg' href='__CTA_HREF__' role='button'>__CTA_LABEL__</a>
    </div>
  </div>
  <div class='row g-4'>
    <div class='col-md-4'>
      <div class='card h-100 shadow-sm'>
        <div class='card-body'>
          <h2 class='h5 card-title'>Templates</h2>
          <p class='card-text mb-0'>Jinja templates are set up under <code>templates/</code>.</p>
        </div>
      </div>
    </div>
    <div class='col-md-4'>
      <div class='card h-100 shadow-sm'>
        <div class='card-body'>
          <h2 class='h5 card-title'>Static</h2>
          <p class='card-text mb-0'>Custom CSS/JS are ready under <code>static/</code>.</p>
        </div>
      </div>
    </div>
    <div class='col-md-4'>
      <div class='card h-100 shadow-sm'>
        <div class='card-body'>
          <h2 class='h5 card-title'>__APP_CARD_TITLE__</h2>
          <p class='card-text mb-0'>Base app factory and route are configured in <code>app.py</code>.</p>
        </div>
      </div>
    </div>
  </div>
{% endblock %}
"""

COMMON_CSS = """body {
  background: linear-gradient(180deg, #f8fafc 0%, #eef2ff 100%);
}

.card {
  border: 0;
  border-radius: 0.9rem;
}

.card-title {
  color: #0d6efd;
}
"""


def create_web_dirs(package_root: Path) -> tuple[Path, Path, Path]:
    templates_dir = package_root / "templates"
    static_css_dir = package_root / "static" / "css"
    static_js_dir = package_root / "static" / "js"

    templates_dir.mkdir(parents=True, exist_ok=True)
    static_css_dir.mkdir(parents=True, exist_ok=True)
    static_js_dir.mkdir(parents=True, exist_ok=True)
    return templates_dir, static_css_dir, static_js_dir


def build_base_html(css_href: str, js_src: str) -> str:
    return BASE_HTML_TEMPLATE.replace("__CSS_HREF__", css_href).replace("__JS_SRC__", js_src)


def build_index_html(description: str, cta_href: str, cta_label: str, app_card_title: str) -> str:
    return (
        INDEX_HTML_TEMPLATE.replace("__DESCRIPTION__", description)
        .replace("__CTA_HREF__", cta_href)
        .replace("__CTA_LABEL__", cta_label)
        .replace("__APP_CARD_TITLE__", app_card_title)
    )


def build_common_js(message: str) -> str:
    return (
        "document.addEventListener('DOMContentLoaded', () => {\n"
        f"  console.log('{message}');\n"
        "});\n"
    )


def build_readme(
    project: str,
    framework_name: str,
    run_command: str,
    open_url: str,
    docs_url: str | None = None,
) -> str:
    docs_block = ""
    if docs_url:
        docs_block = f"Docs: {docs_url}\n"

    return (
        f"# {project}\n\n"
        f"{framework_name} starter generated by Optimation CLI.\n\n"
        "## Requirements\n\n"
        "- Python 3.11+\n"
        "- pip\n\n"
        "## Installation\n\n"
        "```bash\n"
        "python -m venv .venv\n"
        ".venv\\Scripts\\activate\n"
        "pip install -r requirements.txt\n"
        "```\n\n"
        "## Run\n\n"
        "```bash\n"
        f"{run_command}\n"
        "```\n\n"
        f"Open: {open_url}\n"
        f"{docs_block}\n"
        "## Project layout\n\n"
        "```text\n"
        f"src/{project}/\n"
        "  app.py\n"
        "  main.py\n"
        "  templates/\n"
        "    base.html\n"
        "    index.html\n"
        "  static/\n"
        "    css/style.css\n"
        "    js/app.js\n"
        "tests/\n"
        "  test_app.py\n"
        "```\n\n"
        "## Test\n\n"
        "```bash\n"
        "pytest\n"
        "```\n"
    )
