from __future__ import annotations

from pathlib import Path


def create_worker_template(root: Path, project: str) -> None:
    package_root = root / "src" / project
    jobs_dir = package_root / "jobs"

    jobs_dir.mkdir(parents=True, exist_ok=True)

    (package_root / "config.py").write_text(
        "from __future__ import annotations\n\n"
        "import os\n\n"
        "def get_env(name: str, default: str = '') -> str:\n"
        "    value = os.getenv(name)\n"
        "    if value is None:\n"
        "        return default\n"
        "    return value.strip()\n",
        encoding="utf-8",
    )

    (jobs_dir / "__init__.py").write_text("", encoding="utf-8")

    (jobs_dir / "sample_job.py").write_text(
        "from __future__ import annotations\n\n"
        "from datetime import datetime, timezone\n\n"
        "def run() -> None:\n"
        "    now = datetime.now(timezone.utc).isoformat()\n"
        "    print(f'[sample_job] automation script executed at {now}')\n",
        encoding="utf-8",
    )

    (package_root / "main.py").write_text(
        "from __future__ import annotations\n\n"
        "try:\n"
        "    from .jobs.sample_job import run\n"
        "except ImportError:\n"
        "    from jobs.sample_job import run\n\n"
        "def main() -> None:\n"
        "    run()\n\n"
        "if __name__ == '__main__':\n"
        "    main()\n",
        encoding="utf-8",
    )

    (root / "requirements.txt").write_text(
        "# Add your automation dependencies here\n",
        encoding="utf-8",
    )

    (root / "README.md").write_text(
        f"# {project}\n\n"
        "Worker automation starter generated by Optimation CLI.\n\n"
        "## Purpose\n\n"
        "Use this template to build automation scripts, scheduled jobs, and internal tooling.\n\n"
        "## Requirements\n\n"
        "- Python 3.11+\n"
        "- pip\n\n"
        "## Installation\n\n"
        "```bash\n"
        "python -m venv .venv\n"
        ".venv\\Scripts\\activate\n"
        "pip install -r requirements.txt\n"
        "```\n\n"
        "## Run sample job\n\n"
        "```bash\n"
        f"python -m src.{project}.main\n"
        "```\n\n"
        "## Project layout\n\n"
        "```text\n"
        f"src/{project}/\n"
        "  config.py\n"
        "  main.py\n"
        "  jobs/\n"
        "    sample_job.py\n"
        "tests/\n"
        "```\n",
        encoding="utf-8",
    )
